import "./globals.css";
import { Inter, Roboto_Mono } from "next/font/google";
import Navigation from "./components/navigation";

const inter = Inter({ subsets: ["latin"] });

const roboto_mono = Roboto_Mono({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-roboto-mono",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <body className={inter.className}> */}
      <body className={roboto_mono.className}>
        <Navigation />
        {children}
      </body>
    </html>
  );
}
